backend:
  name: github
  branch: main # change this to your branch
  repo: M-erb/decapcms-astro-demo # change this to your repo
  site_domain: decapcms-astro-demo.pages.dev # change this to your domain
  base_url: https://decapcms-astro-demo.pages.dev # change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration
media_folder: public/uploads
public_folder: /uploads
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/content/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
